### ISSUE TITLE
Suggestion - Add Option to use the current months TMX BG

### ISSUE THREAD

**Issue by skybaks** [XertroV/tm-menu-bg-chooser#1]
The TMX background for this month is: https://images.mania-exchange.com/next/backgrounds/22-07/bg.jpg
This is usually a decently quality background image and they also update the location consistently in the format `YY-MM/bg.jpg`.
All previous month's backgrounds are also still available by changing the URL, maybe there could be an option to pick from those at random?

**Comment by XertroV** [comment]
> All previous month's backgrounds are also still available by changing the URL, maybe there could be an option to pick from those at random?

If it's possible to do the current one, then this is almost certainly possible. I'll look into it and see if it works. If so, should be easy to implement.

Preliminary analysis seems promising:

![image](https://user-images.githubusercontent.com/1046448/177004528-ed664a77-6f2d-4a60-9b93-5e062a5969e6.png)

**Comment by XertroV** [comment]
I'm going to ignore ultrawide issues for the moment and just focus on current image then: either a particular m/y selection or randomized. Planned for tomorrow (it's sleep time for me atm)

**Comment by zai-tm** [comment]
I'm famous

**Comment by XertroV** [comment]
Implemented in v1.0.0: load current month's bg or randomize

![image](https://user-images.githubusercontent.com/1046448/177027876-3743d725-b21a-405a-96d9-251b73de5a07.png)
